/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(clk, rst, in_halt);
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:22" *)
  wire [4:0] \$1 ;
  (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:7" *)
  reg [3:0] cnt = 4'h0;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:7" *)
  reg [3:0] \cnt$next ;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:9" *)
  reg [4:0] cnt_next;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:8" *)
  reg cnt_ovf = 1'h0;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:8" *)
  reg \cnt_ovf$next ;
  (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:11" *)
  input in_halt;
  wire in_halt;
  (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  assign \$1  = cnt + (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:22" *) 1'h1;
  always @(posedge clk)
    cnt <= \cnt$next ;
  always @(posedge clk)
    cnt_ovf <= \cnt_ovf$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    { \cnt_ovf$next , \cnt$next  } = cnt_next;
    (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
        begin
          \cnt$next  = 4'h0;
          \cnt_ovf$next  = 1'h0;
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    cnt_next = \$1 ;
    (* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:25" *)
    casez (in_halt)
      /* src = "/data/Github/SNUHSD2023Spring/Lab4/dup_comb.py:25" */
      1'h1:
          cnt_next = cnt_next;
    endcase
  end
endmodule
