/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(in_b, out_d, out_ovf, in_a);
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:17" *)
  wire [4:0] \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:8" *)
  input [3:0] in_a;
  wire [3:0] in_a;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:9" *)
  input [3:0] in_b;
  wire [3:0] in_b;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:10" *)
  output [3:0] out_d;
  wire [3:0] out_d;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:11" *)
  output out_ovf;
  wire out_ovf;
  assign \$1  = in_a + (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/adder.py:17" *) in_b;
  assign { out_ovf, out_d } = \$1 ;
endmodule
