/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(in_bool_1, in_bool_2, out_bool, in_bool_0);
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:18" *)
  wire \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:18" *)
  wire \$3 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:18" *)
  wire \$5 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:9" *)
  input in_bool_0;
  wire in_bool_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:9" *)
  input in_bool_1;
  wire in_bool_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:9" *)
  input in_bool_2;
  wire in_bool_2;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:11" *)
  output out_bool;
  wire out_bool;
  assign \$3  = \$1  & (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:18" *) in_bool_1;
  assign \$5  = \$3  & (* src = "/data/Github/HardwareSystemDesign/Lab3/Example/test_array.py:18" *) in_bool_2;
  assign out_bool = \$5 ;
  assign \$1  = in_bool_0;
endmodule
