/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(in_data_4_1, in_data_4_2, in_data_4_3, in_ovf_4_0, in_ovf_4_1, in_ovf_4_2, in_ovf_4_3, in_valid_4_0, in_valid_4_1, in_valid_4_2, in_valid_4_3, out_d, out_ovf, out_valid, in_data_4_0);
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:41" *)
  wire [8:0] \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  input [7:0] in_data_4_0;
  wire [7:0] in_data_4_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  input [7:0] in_data_4_1;
  wire [7:0] in_data_4_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  input [7:0] in_data_4_2;
  wire [7:0] in_data_4_2;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  input [7:0] in_data_4_3;
  wire [7:0] in_data_4_3;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:20" *)
  input in_ovf_4_0;
  wire in_ovf_4_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:20" *)
  input in_ovf_4_1;
  wire in_ovf_4_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:20" *)
  input in_ovf_4_2;
  wire in_ovf_4_2;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:20" *)
  input in_ovf_4_3;
  wire in_ovf_4_3;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:22" *)
  input in_valid_4_0;
  wire in_valid_4_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:22" *)
  input in_valid_4_1;
  wire in_valid_4_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:22" *)
  input in_valid_4_2;
  wire in_valid_4_2;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:22" *)
  input in_valid_4_3;
  wire in_valid_4_3;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:24" *)
  output [7:0] out_d;
  wire [7:0] out_d;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:25" *)
  output out_ovf;
  wire out_ovf;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:26" *)
  input out_valid;
  wire out_valid;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:24" *)
  wire [7:0] tree_l_out_d;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:24" *)
  wire [7:0] tree_r_out_d;
  assign \$1  = $signed(tree_l_out_d) + (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:41" *) $signed(tree_r_out_d);
  tree_l tree_l (
    .out_d(tree_l_out_d)
  );
  tree_r tree_r (
    .out_d(tree_r_out_d)
  );
  assign { out_ovf, out_d } = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.tree_l" *)
(* generator = "Amaranth" *)
module tree_l(out_d);
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:47" *)
  wire [8:0] \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  wire [7:0] in_data_2_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  wire [7:0] in_data_2_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:24" *)
  output [7:0] out_d;
  wire [7:0] out_d;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:25" *)
  wire out_ovf;
  assign in_data_2_0 = 8'h00;
  assign in_data_2_1 = 8'h00;
  assign { out_ovf, out_d } = \$1 ;
  assign \$1  = 9'h000;
endmodule

(* \amaranth.hierarchy  = "top.tree_r" *)
(* generator = "Amaranth" *)
module tree_r(out_d);
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:47" *)
  wire [8:0] \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  wire [7:0] in_data_2_0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:18" *)
  wire [7:0] in_data_2_1;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:24" *)
  output [7:0] out_d;
  wire [7:0] out_d;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/adder_tree.py:25" *)
  wire out_ovf;
  assign in_data_2_0 = 8'h00;
  assign in_data_2_1 = 8'h00;
  assign { out_ovf, out_d } = \$1 ;
  assign \$1  = 9'h000;
endmodule
