/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(in_a_valid, in_b, in_b_valid, out_d, out_d_valid, out_ovf, clk, rst, in_a);
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:28" *)
  wire \$1 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire \$10 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire \$13 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:32" *)
  wire [7:0] \$17 ;
  (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ast.py:249" *)
  wire [7:0] \$19 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:32" *)
  wire [8:0] \$21 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire \$23 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:30" *)
  wire [7:0] \$3 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:30" *)
  wire [8:0] \$5 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire [8:0] \$7 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire \$8 ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *)
  wire \$9 ;
  (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:12" *)
  input [3:0] in_a;
  wire [3:0] in_a;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:13" *)
  input in_a_valid;
  wire in_a_valid;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:14" *)
  input [3:0] in_b;
  wire [3:0] in_b;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:15" *)
  input in_b_valid;
  wire in_b_valid;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:21" *)
  output [7:0] out_d;
  reg [7:0] out_d = 8'h00;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:21" *)
  reg [7:0] \out_d$next ;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:22" *)
  input out_d_valid;
  wire out_d_valid;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:23" *)
  output out_ovf;
  reg out_ovf = 1'h0;
  (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:23" *)
  reg \out_ovf$next ;
  (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  assign \$10  = in_b[3] ^ (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) in_a[3];
  assign \$9  = ~ (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) \$10 ;
  assign \$13  = \$9  ^ (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) out_d[7];
  assign \$8  = ~ (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) \$13 ;
  assign \$7  = + (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) \$8 ;
  assign \$17  = $signed(in_b) * (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:32" *) $signed(in_a);
  assign \$1  = in_a_valid & (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:28" *) in_b_valid;
  assign \$19  = + (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/ast.py:249" *) out_d[6];
  assign \$21  = $signed(\$17 ) + (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:32" *) $signed(\$19 );
  assign \$23  = $signed(\$7 ) == (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:31" *) $signed(\$21 );
  assign \$3  = $signed(in_b) * (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:30" *) $signed(in_a);
  assign \$5  = $signed(\$3 ) + (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:30" *) $signed(out_d);
  always @(posedge clk)
    out_d <= \out_d$next ;
  always @(posedge clk)
    out_ovf <= \out_ovf$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \out_d$next  = out_d;
    \out_ovf$next  = out_ovf;
    (* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:28" *)
    casez (\$1 )
      /* src = "/data/Github/HardwareSystemDesign/Lab3/Practice/mac.py:28" */
      1'h1:
        begin
          \out_d$next  = \$5 [7:0];
          \out_ovf$next  = \$23 ;
        end
    endcase
    (* src = "/usr/local/lib/python3.10/dist-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
        begin
          \out_d$next  = 8'h00;
          \out_ovf$next  = 1'h0;
        end
    endcase
  end
endmodule
